apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-cs
  labels:
    app: desafio-cs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: desafio-cs
  template:
    metadata:
      labels:
        app: desafio-cs
    spec:
      containers:
        - name: desafio-cs
          image: 565715204981.dkr.ecr.sa-east-1.amazonaws.com/desafio:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: desafio-cs-service
spec:
  type: NodePort
  selector:
    app: desafio-cs
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000